-- Woerterbuch-Import (mit Querverweis-Links) 53/53: 18 Eintraege
insert into woerter (slug, wort, artikel, ipa, wortart, kategorie, definition, bedeutungen, beispiel) values
  ('fpoe', 'FPÖ', '', '', '', '', 'FPÖ', '[{"kategorie": "wörtlich, Abkürzung für", "text": "\"Freiheitliche Partei Österreichs\" = \"eine der größten und bedeutendsten politischen Parteien in Österreich mit Parteizentrale am [[Friedrich-Schmidt-Platz]] 4\""}, {"kategorie": "", "text": "Die FPÖ wurde 1956 als Nachfolgerin des \"Verbandes der Unabhängigen\" (VdU) gegründet und vertritt konservative bis rechtspopulistische Ideologien mit besonderem Fokus auf Themen wie nationale Souveränität, restriktive Migrationspolitik und den Schutz traditioneller österreichischer Werte"}, {"kategorie": "", "text": "Unter der Führung von Jörg Haider, der 1986 zum Parteivorsitzenden gewählt wurde, erlebte die FPÖ eine radikale ideologische Wende und einen starken Aufschwung. Haider setzte auf einen populistischen Stil, betonte nationale Identität und wandte sich gegen Immigration und die etablierte politische Elite. Dies brachte der Partei in den 1990er Jahren und 2000er Jahren beträchtlichen Wahlerfolg, aber auch internationale Kritik"}, {"kategorie": "", "text": "Die Freiheitliche Partei Österreichs (FPÖ) hat im Laufe ihrer Geschichte mehrere bedeutende Persönlichkeiten hervorgebracht, die die Partei maßgeblich geprägt und die österreichische Politik beeinflusst haben. Hier sind einige der wichtigsten Persönlichkeiten der FPÖ: (A) Friedrich Peter (1921-2005, Parteiobmann der FPÖ 1958–1978, Mitglied des Nationalrats);  (B) Jörg Haider (1950-2008, Parteiobmann der FPÖ 1986–2000, Landeshauptmann von Kärnten 1989–1991, 1999–2008);  (C) Norbert Steger (geb. 1944, Parteiobmann der FPÖ 1980–1986, Vizekanzler und Handelsminister 1983–1987);  (D) Heinz-Christian-Strache (geb. 1969, Parteiobmann der FPÖ 2005–2019, Vizekanzler 2017–2019)"}]'::jsonb, ''),
  ('schmealingplotz', 'Schmealingplotz', '', '', '', '', 'Schmerlingplatz', '[{"kategorie": "allg.", "text": "bedeutender öffentlicher Platz im 1. Wiener Gemeindebezirk ([[Innere]] Stadt)"}, {"kategorie": "", "text": "Er liegt zentral zwischen dem [[Wiener]] Rathaus und dem [[österreichischen]] Parlamentsgebäude und bildet einen wichtigen Knotenpunkt im politischen und administrativen Herzen Wiens"}, {"kategorie": "", "text": "Der Schmerlingplatz wurde im 19. Jahrhundert im Zuge der Errichtung der Wiener Ringstraße angelegt, einer Zeit intensiver städtebaulicher Entwicklung. Benannt ist der Platz nach Anton von Schmerling (1805–1893), einem bedeutenden österreichischen Politiker und Justizminister, der als einer der Hauptverantwortlichen für die Schaffung der österreichischen Verfassung von 1867 gilt"}, {"kategorie": "", "text": "Direkt am Schmerlingplatz befindet sich der monumentale [[Justizpalast]]. Er ist der Sitz des Obersten Gerichtshofs, des Oberlandesgerichts Wien und weiterer wichtiger Justizeinrichtungen. Das Gebäude wurde zwischen 1875 und 1881 im Neorenaissance-Stil erbaut und ist ein markantes Beispiel für die prunkvolle Architektur der Ringstraße."}]'::jsonb, ''),
  ('schdodthalle', 'Schdodthalle', '', '', '', '', 'Stadthalle', '[{"kategorie": "wörtlich, kurz für", "text": "\"Wiener Stadthalle\" = \"größte multifunktionale Veranstaltungshalle in Wien und eine der bedeutendsten Veranstaltungsorte in Österreich\""}, {"kategorie": "", "text": "Sie befindet sich im 15. Wiener Gemeindebezirk ([[Rudolfsheim-Fünfhaus]]) und ist bekannt für eine Vielzahl von Veranstaltungen, darunter Konzerte, Sportereignisse, Messen, Shows und Kongresse"}, {"kategorie": "", "text": "Die Wiener Stadthalle wurde zwischen 1953 und 1958 nach den Plänen des österreichischen Architekten Roland Rainer errichtet. Die Eröffnung fand 1958 statt. Das Gebäude ist ein herausragendes Beispiel für die Nachkriegsarchitektur in Österreich und wurde für seine moderne und funktionale Gestaltung mehrfach ausgezeichnet"}, {"kategorie": "", "text": "Die Anlage umfasst mehrere Hallen, die für unterschiedliche Zwecke genutzt werden können, sowie ein Stadthallenbad, das ein beliebtes öffentliches Schwimmbad ist. Die Haupthalle, auch Halle D genannt, ist mit einem Fassungsvermögen von bis zu 16.000 Personen die größte und wichtigste Halle der Anlage."}]'::jsonb, ''),
  ('schdadion', 'Schdadion', '', '', '', '', 'Stadion', '[{"kategorie": "wörtlich, kurz für", "text": "\"Wiener Stadion\" = \"größtes und bekanntestes Stadion in Wien sowie das größte in Österreich\" (offiziell bekannt als [[Ernst-Happel-Stadion]])"}, {"kategorie": "", "text": "Es befindet sich im 2. Wiener Gemeindebezirk ([[Leopoldstadt]]) im Bereich des [[Praters]]"}, {"kategorie": "", "text": "Das Stadion ist ein bedeutendes Wahrzeichen der Stadt und ein zentraler Ort für sportliche und kulturelle Großveranstaltungen"}, {"kategorie": "", "text": "Das Stadion wurde ursprünglich als [[Praterstadion]] zwischen 1929 und 1931 errichtet und war eine der größten Sportanlagen seiner Zeit. Es wurde anlässlich der zweiten Arbeiterolympiade gebaut und war ein Symbol für die sozialen und sportlichen Errungenschaften der Zwischenkriegszeit in Österreich"}, {"kategorie": "", "text": "Im Jahr 1992 wurde das Stadion zu Ehren des berühmten österreichischen Fußballtrainers Ernst Happel, der international große Erfolge feierte, in Ernst-Happel-Stadion umbenannt"}, {"kategorie": "", "text": "Das Stadion zeichnet sich durch seine markante elliptische Form und das große, geschwungene Dach aus, das fast alle Tribünenplätze überdeckt. Mit einer maximalen Kapazität von etwa 50.000 Zuschauern ist es das größte Stadion in Österreich."}]'::jsonb, ''),
  ('proodaschdadion', 'Proodaschdadion', '', '', '', '', 'Praterstadion', '[{"kategorie": "allg.", "text": "\"größtes und bekanntestes Stadion in Wien sowie das größte in Österreich\" (offiziell bekannt als [[Ernst-Happel-Stadion]] bzw. [[Wiener Stadion]])"}, {"kategorie": "", "text": "Es befindet sich im 2. Wiener Gemeindebezirk ([[Leopoldstadt]]) im Bereich des [[Praters]]"}, {"kategorie": "", "text": "Das Stadion ist ein bedeutendes Wahrzeichen der Stadt und ein zentraler Ort für sportliche und kulturelle Großveranstaltungen"}, {"kategorie": "", "text": "Das Stadion wurde ursprünglich als [[Praterstadion]] zwischen 1929 und 1931 errichtet und war eine der größten Sportanlagen seiner Zeit. Es wurde anlässlich der zweiten Arbeiterolympiade gebaut und war ein Symbol für die sozialen und sportlichen Errungenschaften der Zwischenkriegszeit in Österreich"}, {"kategorie": "", "text": "Im Jahr 1992 wurde das Stadion zu Ehren des berühmten österreichischen Fußballtrainers Ernst Happel, der international große Erfolge feierte, in Ernst-Happel-Stadion umbenannt"}, {"kategorie": "", "text": "Das Stadion zeichnet sich durch seine markante elliptische Form und das große, geschwungene Dach aus, das fast alle Tribünenplätze überdeckt. Mit einer maximalen Kapazität von etwa 50.000 Zuschauern ist es das größte Stadion in Österreich."}]'::jsonb, ''),
  ('ghaam', 'ghaam', '', '', '', '', 'geheim', '[{"kategorie": "wörtlich", "text": "\"geheim\" (verkürzte Ableitung vom mittelhochdeutschen \"geheim\"=\"heimlich\")"}, {"kategorie": "allg.", "text": "mysteriös, rätselhaft, verdeckt, verborgen"}]'::jsonb, 'Zwa Valiabte in da Ghaam!'),
  ('ghaama', 'Ghaama', '', '', '', '', 'Ghamer', '[{"kategorie": "wörtlich", "text": "\"Geheimer\" (verkürzte Ableitung vom mittelhochdeutschen \"geheim\"=\"heimlich\")"}, {"kategorie": "Gaunersprache", "text": "Geheimpolizist, verdeckter Ermittler"}]'::jsonb, ''),
  ('giarrn', 'giarrn', '', '', '', '', 'girren', '[{"kategorie": "wörtlich", "text": "\"gurren\" (vom mittelhochdeutschen \"girren\"=\"gurren\")"}, {"kategorie": "fig.", "text": "\"kokettierend sprechen\", flirten, schäkern"}]'::jsonb, ''),
  ('eislutschka', 'Eislutschka', '', '', '', '', 'Eislutschker', '[{"kategorie": "wörtlich", "text": "\"Eis am Stiel\" (von \"Lutschker\"=\"lutschendes Kind\")"}, {"kategorie": "allg.", "text": "Stieleis, \"Schleckstengel\", [[Gfruarans]]"}]'::jsonb, 'von foabige Eislutschka traaman'),
  ('gschlaudabua', 'Gschlaudabua', '', '', '', '', 'Gschlauderbub', '[{"kategorie": "wörtlich", "text": "\"Geschladerjunge\" (vom mittelhochdeutschen \"slœeteren\"=\"Schmutzwasser verspritzen\")"}, {"kategorie": "scherzhaft für", "text": "\"Schmuddeljunge\", \"Dreckspatz\", \"Schlabbermax\", \"Schlampsack\", [[Schlampertatsch]] (schlampig und ungepflegt aussehender Bursche)"}]'::jsonb, 'Dea kummd dahea wiara Gschlaudabua!'),
  ('ollidoogwaund', 'Ollidoogwaund', '', '', '', '', 'Alletag-Gewand', '[{"kategorie": "wörtlich", "text": "\"Alle-Tage-Gewand\" (Determinativkompositum aus \"Alle-Tage\"=\"Alltags-…\" und \"Gewand\"=\"Kleidung\")"}, {"kategorie": "scherzhaft für", "text": "\"Alltagskluft\", \"Tagesklamotten\", \"Immer-und-Überall-Gewand\", \"Schlabber-Look\""}]'::jsonb, 'Im Ollidoogwaund geed ma ned zua Hochzeit!'),
  ('howan', 'Howan', '', '', '', '', 'Habern', '[{"kategorie": "wörtlich", "text": "\"Hafer\" (vom mittelhochdeutschen \"haber\"=\"Hafer\")"}, {"kategorie": "bot.", "text": "echter Hafer, Saathafer (lateinischer Name: \"Avena sativa\")"}]'::jsonb, ''),
  ('kistnschinda', 'Kistnschinda', '', '', '', '', 'Kistenschinder', '[{"kategorie": "wörtlich", "text": "\"Klangkastenmalträtierer\" (Determinativkompositum aus \"Kiste\"=\"Klangkasten\" und \"Schinder\"=\"Quäler\")"}, {"kategorie": "mus., scherzhaft für", "text": "\"Tastenklopfer\", \"Klavierknecht\", \"Saitenkistenhämmerer\", \"Klangkastenbändiger\""}]'::jsonb, 'Kistnschinda, hau eine in de Tastn!'),
  ('lamuahaatscha', 'Lamuahaatscha', '', '', '', 'Wienerisches aus Musik, Kunst, Kultur & Medien', 'Lamurhatscher', '[{"kategorie": "wörtlich", "text": "\"L''amour-Hatscher\" (Determinativkompositum aus \"l''amour\"=\"Liebe\" und \"Hatscher\"=\"längerer, beschwerlicher Fußmarsch\" [vom arabischen \"Haddsch\"=\"islamischer Pilgermarsch nach Mekka\", der oft als sehr anstrengend und beschwerlich beschrieben wird])"}, {"kategorie": "scherzhaft für", "text": "\"langsamer Tanz\", \"Schmusetanz\" (romantisch langsames Musikstück, zu dem man eng umschlungen tanzt), \"Liebestänzchen\", \"Knutsch-Schlurfer\" , \"Gspusi-Schieber\" (=langsamer, enger Endlos-Tanz)"}]'::jsonb, ''),
  ('tohuwabohu', 'Tohuwabohu', '', '', '', 'Jiddische Sprachperlen im Wienerischen', 'Tohuwabohu', '[{"kategorie": "wörtlich", "text": "\"heilloses Durcheinander\" (von den hebräischen Worten \"tohu\" (תֹהוּ, \"Leere\", \"Chaos\") und \"bohu\" (בֹּהוּ, \"Ödnis\", \"Nichtigkeit\")"}, {"kategorie": "fig.", "text": "Durcheinander, Chaos, Unordnung, Wirrwarr, Kuddelmuddel"}]'::jsonb, 'Wea soi si in den Tohuwabohu no ausseseeng?'),
  ('blatti', 'Blatti', '', '', '', 'Wiener Gaunersprache', 'Blatti', '[{"kategorie": "wörtlich", "text": "\"Bargeld\" (Verballhornung des tschechischen \"platit\"=\"zahlen\")"}, {"kategorie": "Gaunersprache", "text": "Geld, Zaster, Kohle, Moneten, [[Marie]], [[Geaschdl]], [[Schooda]]"}]'::jsonb, 'Reib ume des Blatti!'),
  ('bleankl', 'Bleankl', '', '', '', 'Wiener Gaunersprache', 'Blenkelnes', '[{"kategorie": "wörtlich", "text": "\"Weißglänzendes\" (vom mittelhochdeutschen \"blenkeln\"=\"weiß glänzen\")"}, {"kategorie": "Gaunersprache", "text": "Geld, Zaster, Kohle, Moneten, [[Marie]], [[Geaschdl]], [[Schooda]]"}]'::jsonb, 'Reib ume des Bleankl!'),
  ('loowo', 'Loowo', '', '', '', 'Wiener Gaunersprache', 'Lowo', '[{"kategorie": "wörtlich, Gaunersprache", "text": "\"Bargeld\" (von Romanes \"lovo\"=\"Geld\")"}, {"kategorie": "allg.", "text": "Geld, Zaster, Kohle, Moneten, [[Marie]], [[Geaschdl]], [[Schooda]]"}]'::jsonb, 'Reib ume des Loowo!')
on conflict (slug) do update set
  wort = excluded.wort,
  artikel = excluded.artikel,
  kategorie = excluded.kategorie,
  definition = excluded.definition,
  bedeutungen = excluded.bedeutungen,
  beispiel = excluded.beispiel;
