-- Migration: Themenkategorie pro Wort ergaenzen (aus Spalte A der Excel-Datei)
alter table woerter add column if not exists kategorie text default '';

update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'owezaan';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'beidlrotz';
update woerter set kategorie = 'Wiener Jugendsprache & Teenie-Talk' where slug = 'kraecka';
update woerter set kategorie = 'Wiener Küche & Gaumenfreuden' where slug = 'topfnbuchtl';
update woerter set kategorie = 'Trinken, Saufen & Tschechern auf Wienerisch' where slug = 'blau';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'draadiwaawal';
update woerter set kategorie = 'Wiener Küche & Gaumenfreuden' where slug = 'eadaepfaenuudln';
update woerter set kategorie = 'Wiener Küche & Gaumenfreuden' where slug = 'fleckaln';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'gaudich';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'gucka';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'haatschn';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'woeoechans';
update woerter set kategorie = 'Sex, Erotik und Bettgeflüster auf Wienerisch' where slug = 'lawuafut';
update woerter set kategorie = 'Sex, Erotik und Bettgeflüster auf Wienerisch' where slug = 'johannistriablarin';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'gneissa';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'muffn';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'ochtl';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'boozad';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'plutzaschaeaedl';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'oag';
update woerter set kategorie = 'Wiener Wörter mit schillernder Geschichte' where slug = 'huebschlarin';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'luluu';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'giggln';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'quaagltreeda';
update woerter set kategorie = 'Trinken, Saufen & Tschechern auf Wienerisch' where slug = 'reischal';
update woerter set kategorie = 'Echte Wiener Schmähperlen' where slug = 'moongschaas';
update woerter set kategorie = 'Wiener Mechaniker-Slang' where slug = 'asfaltduttl';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'schnoizn';
update woerter set kategorie = 'Trinken, Saufen & Tschechern auf Wienerisch' where slug = 'auduusld';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'ausuudan';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'deamoin';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'eifian';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'gschissn';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'wossa';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'voiholla';
update woerter set kategorie = 'Wiener Küche & Gaumenfreuden' where slug = 'aupassian';
update woerter set kategorie = 'Grundwortschatz Wienerisch' where slug = 'neafnbinkal';