// Die 45 Themenkategorien aus Spalte A der Wörterbuch-Excel-Datei.
export const ALLE_KATEGORIEN = [
  "Grundwortschatz Wienerisch",
  "Wiener Sprüche, die sitzen!",
  "Echt wienerisch – so sagt man das in Wien!",
  "Jiddische Sprachperlen im Wienerischen",
  "Wiener Gefühlsäußerungen & Kult-Sager",
  "Wiener Fußballer- und Sportlerjargon",
  "Wiener Gaunersprache",
  "Wiener Wörter mit schillernder Geschichte",
  "Botanik und Pflanzen auf Wienerisch",
  "Viecher und Tiernamen auf Wienerisch",
  "Wiener Küche & Gaumenfreuden",
  "Wiener Kaffeehaus-ABC",
  "Echte Wiener Schmähperlen",
  "Schimpfen und Fluchen auf Wienerisch",
  "Wiener Würstelstandjargon",
  "Wienerisches aus Musik, Kunst, Kultur & Medien",
  "Krank & kuriert auf Wienerisch",
  "Handwerk und Beruf – so sagt's der Wiener!",
  "Wiener Jugendsprache & Teenie-Talk",
  "Sex, Erotik und Bettgeflüster auf Wienerisch",
  "Wiener Kartentipplerjargon",
  "Wiener Mechaniker-Slang",
  "Tod und Sterben auf Wienerisch",
  "Trinken, Saufen & Tschechern auf Wienerisch",
  "Wiener Fleischhauer-Slang",
  "Religiöses & Göttliches auf Wienerisch",
  "Wiener Wahrzeichen & Sehenswürdigkeiten",
  "Wiener Architektur & Baukunst",
  "Wiener Gemeindebauten",
  "Wiener Prachtpalais",
  "Wiener Gassen, Straßen & Plätze",
  "Wiener Donau-, Donaukanal- und Wienfluss-Brücken",
  "Wiener Kirchen & Gotteshäuser",
  "Wiener Friedhöfe & Gottesacker",
  "Wiener Denkmäler & steinerne Zeitzeugen",
  "Wiener Parks und Parkanlagen",
  "Wiener Theater, Bühnen und Aufführungsstätten",
  "Wiener Erzherzöge, Könige & Kaiser",
  "Wiener Glanzstücke, Kulturschätze & Kunstjuwelen",
  "Wiener Museen & Ausstellungsstätten",
  "Wiener Stadtgeschichte",
  "Wiener Politik & Regierung",
  "Wiener Recht & Gerichtsbarkeit",
  "Wiener Adelstitel und Privilegien",
  "Wiener Prachtpalais und Prunkbauten",
] as const;
